# Site settings
title: rave78
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Technical blog about artificial intelligence, pattern recognition, neural networks and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rave78.github.io" # the base hostname & protocol for your site
twitter_username: rave78
github_username:  rave78

# Build settings
markdown: kramdown

# python code
pygments: true
